### ISSUE TITLE
Multiple Scan-Angets

### ISSUE THREAD

**Issue by urskog84** [phpipam-docker/phpipam-docker#33]
Hello

how can I get multiple scan agent to work.

After looking around, I can see the setting "set agent key" ex: `$config['key']` in in the Agent repo.
https://github.com/phpipam/phpipam-agent/blob/9d62568ab188aa82289424e77776b77133e03b13/config.dist.php#L13

but it it not implemented in the config when running it in docker.

Pleas add environment variable to set the key ex: `IPAM_AGENT_KEY`

```YAML
---
version: '3'

services:
  phpipam-cron:
    #build: .
    image: phpipam/phpipam-cron:latest
    environment:
        - TZ=Europe/London
        - IPAM_DATABASE_HOST=mysql-infra-prod-01.privatelink.mysql.database.azure.com
        - IPAM_DATABASE_USER=phpipam
        - IPAM_DATABASE_PASS=i6fr4vcV%DyfVw48CFNE!sFj3JjzX$$^j
        - IPAM_DATABASE_NAME=phpipamdb
        - SCAN_INTERVAL=5m
        - IPAM_AGENT_KEY='IcPoHPEnQnkK0D2jOgsQXaDGJZFHQ9Bt'
    restart: unless-stopped`
```
