### ISSUE TITLE
Latest mariadb docker breaks the system

### ISSUE THREAD

**Issue by kmadaras** [phpipam-docker/phpipam-docker#46]
If matiadb:latest is applied to a working installation it no longer works.  

Error is: Could not connect to database! SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers

**Comment by alteriks** [comment]
Using `:latest` tag is asking for trouble and shouldn't be used especially for DBs.
Yesterday I deployed phpipam on my laptop, at that time `:latest` pointed to `11.2.3`.
Today latest is `11.3.2` and I'm getting the same error.

@kmadaras please try pinning mariadb to `11.2.3`

**Comment by elmobp** [comment]
hiya i had same issue im using kubernetes but here is steps for k8s you can use similar for normal docker.. 

Create a file locally called my.cnf
```
[client]
default-character-set=utf8

[mysql]
default-character-set=utf8


[mysqld]
collation-server = utf8_unicode_ci
character-set-server = utf8
```

Create the configmap in phpipam namespace
```bash
kubectl create configmap -n phpipam mysql-config --from-file=my.cnf
```

Edit the deployment for mariadb and add the config map
```bash
kubectl edit deployment -n phpipam mariadb
```

```yaml
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: phpipam-db-data
        - mountPath: /etc/mysql/conf.d
          name: config-volume
....
      volumes:
      - configMap:
          defaultMode: 420
          name: mysql-config
          optional: true
        name: config-volume

```

That will do a new deployment and things will start working again.. If you using docker just create a mount inside the container that points at the my.cnf and make sure its on the conf.d folder

**Comment by kmadaras** [comment]
Ended up lockiong it to a version.

**Comment by kmadaras** [comment]
> hiya i had same issue im using kubernetes but here is steps for k8s you can use similar for normal docker..
> 
> Create a file locally called my.cnf
> 
> ```
> [client]
> default-character-set=utf8
> 
> [mysql]
> default-character-set=utf8
> 
> 
> [mysqld]
> collation-server = utf8_unicode_ci
> character-set-server = utf8
> ```
> 
> Create the configmap in phpipam namespace
> 
> ```shell
> kubectl create configmap -n phpipam mysql-config --from-file=my.cnf
> ```
> 
> Edit the deployment for mariadb and add the config map
> 
> ```shell
> kubectl edit deployment -n phpipam mariadb
> ```
> 
> ```yaml
>         volumeMounts:
>         - mountPath: /var/lib/mysql
>           name: phpipam-db-data
>         - mountPath: /etc/mysql/conf.d
>           name: config-volume
> ....
>       volumes:
>       - configMap:
>           defaultMode: 420
>           name: mysql-config
>           optional: true
>         name: config-volume
> ```
> 
> That will do a new deployment and things will start working again.. If you using docker just create a mount inside the container that points at the my.cnf and make sure its on the conf.d folder

Thanks for this!

**Comment by ldod-lle** [comment]
For us Docker/Podman users, I took kmadaras' hint, and translated into Docker:

   ```yaml
    phpipam-mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my_secret_mysql_root_pass
    restart: unless-stopped
    volumes:
      - phpipam-db-data:/var/lib/mysql
      - /opt/phpipam:/etc/mysql/conf.d
 ```
I dropped the "my.cnf" file in the path defined in /opt/phpipam, but obviously set to this whatever you want.  :smile:
