### ISSUE TITLE
Ping not working

### ISSUE THREAD

**Issue by MPueschel** [phpipam-docker/phpipam-docker#52]
Neither the ping in the web interface nor via cron works.

My docker compose yml looks like this:
```
services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    container_name: phpipam-web
    ports:
      - 8082:80
    environment:
      - TZ=Europe/Berlin
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=secret
      - IPAM_DATABASE_WEBHOST=%
    restart: unless-stopped
    security_opt:
        - no-new-privileges:true
    cap_add:
        - NET_ADMIN
        - NET_RAW
    volumes:
      - /home/ubuntu/Docker/phpIPAM/Data/logo:/phpipam/css/images/logo
      - /home/ubuntu/Docker/phpIPAM/Data/ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    container_name: phpipam-cron
    environment:
      - TZ=Europe/Berlin
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=secret
      - SCAN_INTERVAL=5m
    restart: unless-stopped
    security_opt:
        - no-new-privileges:true
    volumes:
      - /home/ubuntu/Docker/phpIPAM/Data/ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb

  phpipam-mariadb:
    image: mariadb:latest
    container_name: phpipam-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=phpipam
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=phpipam
    restart: unless-stopped
    security_opt:
        - no-new-privileges:true
    volumes:
      - /home/ubuntu/Docker/phpIPAM/Data/DB:/var/lib/mysql
```

The log files look like this:
phpipam-web:
Info: Setting timezone to Europe/Berlin

AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.20.0.4. Set the 'ServerName' directive globally to suppress this message

AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.20.0.4. Set the 'ServerName' directive globally to suppress this message

[Sun Feb 09 22:20:05.464201 2025] [mpm_prefork:notice] [pid 21:tid 21] AH00163: Apache/2.4.62 (Unix) PHP/8.3.15 OpenSSL/3.3.2 configured -- resuming normal operations

[Sun Feb 09 22:20:05.464218 2025] [core:notice] [pid 21:tid 21] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND -c Alias "/" "/phpipam/"'

192.168.30.51 - - [09/Feb/2025:22:22:03 +0100] "POST /app/subnets/scan/subnet-scan-execute.php HTTP/1.1" 200 176 "http://192.168.20.108:8082/subnets/3/7/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0"

192.168.30.51 - - [09/Feb/2025:22:24:42 +0100] "POST /app/subnets/scan/subnet-scan-execute.php HTTP/1.1" 200 176 "http://192.168.20.108:8082/subnets/3/7/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0"

phpipam-cron:
Info: Setting timezone to Europe/Berlin
crond: crond (busybox 1.36.1) started, log level 8
crond: USER apache pid  51 cmd /usr/bin/php /phpipam/functions/scripts/discoveryCheck.php
crond: USER apache pid  52 cmd /usr/bin/php /phpipam/functions/scripts/pingCheck.php
crond: USER apache pid  53 cmd /usr/bin/php /phpipam/functions/scripts/resolveIPaddresses.php
pingCheck: No addresses to check
discoveryCheck: Scan start, 254 IPs
discoveryCheck: Scan complete, 0 new hosts
