### ISSUE TITLE
Alpine + php versions & Missing functionality.

### ISSUE THREAD

**Issue by Kierio** [phpipam-docker/phpipam-docker#55]
Because you're pulling "php" from alpine, it pulls the latest version, and consequently phpipam runs and says "Hey, I don't run on the very very very newest version of php btw."

Additionally, php mcrypt is missing from the docker image, preventing users from configuring SAML2.

I'm currently upgrading from 1.3 and can only go as far as 1.4.7 becuase of the first issue. Figured I'd use Docker rather than jumping through a thousand different versions / building from source and having residule files everywhere, but this image is letting me down.

**Comment by GaryAllan** [comment]
The base image is designed to run the latest version of phpIPAM. It doesn't depend on mcrypt.

You can jump straight from 1.3 to latest.

**Comment by Kierio** [comment]
Weird... here I am running phpipam 1.7x and it complains about not yet being supported on the super duper latest version of PHP.

(Because like I said, you're pulling the super latest version of `php` in your Alpine image, running whatever version is in the Alpine repos, rather than specifying an exact version of php known to work with ipam.)

<img width="611" height="271" alt="Image" src="https://github.com/user-attachments/assets/f9743cce-4268-4210-b6f6-b5bdd31ab843" />


Docker log output, couple warnings, fine
```
Info: Setting timezone to Europe/London
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.31.0.6. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.31.0.6. Set the 'ServerName' directive globally to suppress this message
[Wed Aug 20 12:45:19.959893 2025] [mpm_prefork:notice] [pid 19:tid 19] AH00163: Apache/2.4.65 (Unix) PHP/8.3.24 OpenSSL/3.5.1 configured -- resuming normal operations
[Wed Aug 20 12:45:19.960876 2025] [core:notice] [pid 19:tid 19] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND -c Alias "/" "/phpipam/"'
[Wed Aug 20 12:45:35.743422 2025] [php:warn] [pid 21:tid 21] [client 172.31.0.2:49604] PHP Warning:  Undefined array key "HTTPS" in /phpipam/functions/classes/class.Common.php on line 1001
[Wed Aug 20 12:45:35.743458 2025] [php:warn] [pid 21:tid 21] [client 172.31.0.2:49604] PHP Warning:  Undefined array key "HTTPS" in /phpipam/functions/classes/class.Common.php on line 1001
[Wed Aug 20 12:45:35.743466 2025] [php:warn] [pid 21:tid 21] [client 172.31.0.2:49604] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 494
[Wed Aug 20 12:45:35.743469 2025] [php:warn] [pid 21:tid 21] [client 172.31.0.2:49604] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 495
[Wed Aug 20 12:45:35.743472 2025] [php:warn] [pid 21:tid 21] [client 172.31.0.2:49604] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 496
[Wed Aug 20 12:45:35.743475 2025] [php:warn] [pid 21:tid 21] [client 172.31.0.2:49604] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 497
[Wed Aug 20 12:45:35.743478 2025] [php:warn] [pid 21:tid 21] [client 172.31.0.2:49604] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 498
[Wed Aug 20 12:45:35.743481 2025] [php:warn] [pid 21:tid 21] [client 172.31.0.2:49604] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 499
[Wed Aug 20 12:45:35.743484 2025] [php:warn] [pid 21:tid 21] [client 172.31.0.2:49604] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 500
[Wed Aug 20 12:45:35.743487 2025] [php:warn] [pid 21:tid 21] [client 172.31.0.2:49604] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 501
172.31.0.2 - - [20/Aug/2025:12:45:35 +0100] "GET / HTTP/1.1" 302 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0"
[Wed Aug 20 12:45:35.823107 2025] [php:warn] [pid 21:tid 21] [client 172.31.0.2:49604] PHP Warning:  Undefined array key "HTTPS" in /phpipam/functions/classes/class.Common.php on line 1001
172.31.0.2 - - [20/Aug/2025:12:45:35 +0100] "GET /index.php?page=login HTTP/1.1" 200 433 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0"
172.31.0.2 - - [20/Aug/2025:12:45:35 +0100] "GET /css//bootstrap/bootstrap-custom.css HTTP/1.1" 200 9860 "https://ipam.foobar.com/index.php?page=login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0"
172.31.0.2 - - [20/Aug/2025:12:45:35 +0100] "GET /css/bootstrap/bootstrap.min.css HTTP/1.1" 200 19744 "https://ipam.foobar.com/index.php?page=login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0"
[Wed Aug 20 12:45:36.020685 2025] [php:warn] [pid 24:tid 24] [client 172.31.0.2:53986] PHP Warning:  Undefined array key "HTTPS" in /phpipam/functions/classes/class.Common.php on line 1001, referer: https://ipam.foobar.com/index.php?page=login
[Wed Aug 20 12:45:36.020742 2025] [php:warn] [pid 24:tid 24] [client 172.31.0.2:53986] PHP Warning:  Undefined array key "HTTPS" in /phpipam/functions/classes/class.Common.php on line 1001, referer: https://ipam.foobar.com/index.php?page=login
[Wed Aug 20 12:45:36.020768 2025] [php:warn] [pid 24:tid 24] [client 172.31.0.2:53986] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 494, referer: https://ipam.foobar.com/index.php?page=login
[Wed Aug 20 12:45:36.020772 2025] [php:warn] [pid 24:tid 24] [client 172.31.0.2:53986] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 495, referer: https://ipam.foobar.com/index.php?page=login
[Wed Aug 20 12:45:36.020775 2025] [php:warn] [pid 24:tid 24] [client 172.31.0.2:53986] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 496, referer: https://ipam.foobar.com/index.php?page=login
[Wed Aug 20 12:45:36.020779 2025] [php:warn] [pid 24:tid 24] [client 172.31.0.2:53986] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 497, referer: https://ipam.foobar.com/index.php?page=login
[Wed Aug 20 12:45:36.020782 2025] [php:warn] [pid 24:tid 24] [client 172.31.0.2:53986] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 498, referer: https://ipam.foobar.com/index.php?page=login
[Wed Aug 20 12:45:36.020785 2025] [php:warn] [pid 24:tid 24] [client 172.31.0.2:53986] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 499, referer: https://ipam.foobar.com/index.php?page=login
[Wed Aug 20 12:45:36.020788 2025] [php:warn] [pid 24:tid 24] [client 172.31.0.2:53986] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 500, referer: https://ipam.foobar.com/index.php?page=login
[Wed Aug 20 12:45:36.020792 2025] [php:warn] [pid 24:tid 24] [client 172.31.0.2:53986] PHP Warning:  Undefined array key "SCRIPT_URL" in /phpipam/functions/classes/class.User.php on line 501, referer: https://ipam.foobar.com/index.php?page=login
172.31.0.2 - - [20/Aug/2025:12:45:36 +0100] "GET /favicon.ico HTTP/1.1" 302 - "https://ipam.foobar.com/index.php?page=login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0"
[Wed Aug 20 12:45:36.080216 2025] [php:warn] [pid 21:tid 21] [client 172.31.0.2:49604] PHP Warning:  Undefined array key "HTTPS" in /phpipam/functions/classes/class.Common.php on line 1001, referer: https://ipam.foobar.com/index.php?page=login
172.31.0.2 - - [20/Aug/2025:12:45:36 +0100] "GET /index.php?page=login HTTP/1.1" 200 433 "https://ipam.foobar.com/index.php?page=login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0"
/start_apache2: line 4: /usr/sbin/update-ca-certificates: not found
Info: Setting timezone to Europe/London
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.31.0.6. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.31.0.6. Set the 'ServerName' directive globally to suppress this message
[Wed Aug 20 12:49:14.813898 2025] [core:warn] [pid 19:tid 19] AH00098: pid file /run/apache2/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Wed Aug 20 12:49:14.820195 2025] [mpm_prefork:notice] [pid 19:tid 19] AH00163: Apache/2.4.65 (Unix) PHP/8.3.24 OpenSSL/3.5.1 configured -- resuming normal operations
[Wed Aug 20 12:49:14.820216 2025] [core:notice] [pid 19:tid 19] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND -c Alias "/" "/phpipam/"'
```

Falling back to 1.4x which does work (verify database checks are all OK, 11.7.2-MariaDB-ubu2404)

Testing my AD Connection, all passes.

<img width="970" height="486" alt="Image" src="https://github.com/user-attachments/assets/e618ccad-2a2b-4c17-aabf-d367f4c7188b" />

I then go to add a new user / search for a user and get

<img width="815" height="372" alt="Image" src="https://github.com/user-attachments/assets/d132e8e7-bb10-4e74-b7c2-38ca050fce79" />

Apart from my credentials are correct (as I've just tested them), and I've tried `FOO\User`, `user@foo.com`, `user` as the username within the setup of the authentication method.

These are the docker logs again

```
172.31.0.2 - - [20/Aug/2025:13:09:52 +0100] "POST /app/admin/users/edit.php HTTP/1.1" 200 2406 "https://ipam.foobar.com/index.php?page=administration&section=users" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0"
172.31.0.2 - - [20/Aug/2025:13:09:54 +0100] "GET /app/admin/users/ad-search-form.php HTTP/1.1" 200 440 "https://ipam.foobar.com/index.php?page=administration&section=users" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0"
[Wed Aug 20 13:09:58.270957 2025] [php7:warn] [pid 26] [client 172.31.0.2:39418] PHP Warning:  ldap_start_tls(): Unable to start TLS: Can't contact LDAP server in /phpipam/functions/adLDAP/src/adLDAP.php on line 655, referer: https://ipam.foobar.com/index.php?page=administration&section=users
172.31.0.2 - - [20/Aug/2025:13:09:58 +0100] "POST /app/admin/users/ad-search-result.php HTTP/1.1" 200 161 "https://ipam.foobar.com/index.php?page=administration&section=users" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0"
[Wed Aug 20 13:10:12.024400 2025] [php7:warn] [pid 28] [client 172.31.0.2:40298] PHP Warning:  ldap_start_tls(): Unable to start TLS: Can't contact LDAP server in /phpipam/functions/adLDAP/src/adLDAP.php on line 655, referer: https://ipam.foobar.com/index.php?page=administration&section=users
172.31.0.2 - - [20/Aug/2025:13:10:11 +0100] "POST /app/admin/users/ad-search-result.php HTTP/1.1" 200 161 "https://ipam.foobar.com/index.php?page=administration&section=users" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0"
```

The ports to the LDAP server are open, I can lookup, ping, tracert to the LDAP server and I've reviewed the rules allowing it access that explicity call out ports 389/636 (LDAP), 53 (DNS), 445/135-139 (SMB), 80/443 (HTTP/S) and various others which I believe are more than enough for it to connect? (SSL is typically done over 443, but likely using 636 in this case)

I've also used `nc` to confirm the ports on the LDAP server are reachable and open.


I've also given IPAM an web SSL cert.

Docker compose config

```
version: '3'

services:
  phpipam-www:
    image: phpipam/phpipam-www:1.4x
    container_name: phpipam-www
    ports:
      - "8443:80"
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=mariadb
      - IPAM_DATABASE_NAME=phpipam_db
      - IPAM_DATABASE_USER=foobar
      - IPAM_DATABASE_PASS=foobar
      - IPAM_DATABASE_WEBHOST=%
      - IPAM_DIABLE_INSTALER=1
    restart: unless-stopped
    networks:
      customnet:
        ipv4_address: 172.31.0.6
    volumes:
      - phpipam-data:/phpipam
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:1.4x
    container_name: phpipam-cron
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=mariadb
      - IPAM_DATABASE_PASS=foobar
      - SCAN_INTERVAL=1h
    restart: unless-stopped
    networks:
      - customnet
    volumes:
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=foobar
    restart: unless-stopped
    networks:
      - customnet
    volumes:
      - phpipam-db-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - customnet

  haproxy:
    container_name: haproxy
    image: haproxy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
     - customnet
    volumes:
      - haproxy-cfg:/usr/local/etc/haproxy
      - haproxy-ssl:/etc/ssl/certs

volumes:
  phpipam-db-data:
  phpipam-data:
  phpipam-ca:
  haproxy-cfg:
  haproxy-ssl:

networks:
  customnet:
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/24
```

haproxy.cfg

```
global
  daemon
  maxconn 256

resolvers mydns
  nameserver ns1 10.51.0.2:53
  nameserver ns2 10.51.0.3:53
  accepted_payload_size 8192

defaults
  mode http
  timeout connect 5000ms
  timeout client  5000ms
  timeout server 60000ms
  option forwardfor

frontend phpipam-rp
  bind *:80
  bind *:443 ssl crt /etc/ssl/certs/cert.pem
  http-request redirect scheme https code 301 unless { ssl_fc }
  default_backend phpipam-www
  http-request del-header X-Forwarded-For

backend phpipam-www
  server s1 172.31.0.6:80 check resolvers mydns init-addr none
  http-request set-header X-Forwarded-Uri %[url]
  http-request set-header X-Forwarded-Port %[dst_port]
  http-request add-header X-Forwarded-Proto https if { ssl_fc }
```

Appreciated 1.4 may not be supported, I forget how I arrived to the conclusion mcrypt was used, but hopefully the issue is resolved in 1.7 if we can fix the php version issue.
